name: DTW-project
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - tqdm
  - python=3.11
  - matplotlib
  - numpy
  - pip
  - jupyter
  - ipykernel
  - numba
  - tensorflow
  - pyarrow
  - scikit-learn
  - pytest
  - h5py
  - click
  - yamllint
  - dtaidistance
